clean:
	@find . -name '.user.yml' -type f -delete
	@find . -name 'package-lock.yml' -type f -delete
	@find . -type d -name 'logs' -exec rm -rf {} +
	@find . -type d -name 'logs' -exec rm -rf {} +
	@find . -type d -name 'dbt_packages' -exec rm -rf {} +
	@find . -type d -name 'target' -exec rm -rf {} +